import {
    Utensils,
    TrainFront,
    Folder,
    Gamepad,
    CookingPot,
    Speech,
    Plane,
    Armchair,
    Book,
    BriefcaseBusiness,
    Hospital,
    Lightbulb,
    Shirt,
    ShoppingCart,
    Tags,
    TramFront,
    Smartphone,
    Wifi,
    Star,
    Vault,
    Ghost,
    Monitor,
    BookImage,
    SquareTerminal,
    Package,
    Music4,
    FlameKindling,
    GlassWater,
    Bot,
    Coffee,
    AlarmClock,
    Plug,
    PiggyBank,
    Gem,
    WashingMachine,
    BedSingle,
    Refrigerator,
    Rose,
    Router,
    ToolCase,
    Glasses,
    Cake,
    Gift,
    NotebookTabs,
    Tickets,
    Wallet,
    Landmark,
    Projector,
    Keyboard,
    Headphones,
    Truck
} from "lucide-react";

export const ICON_MAP = {
    "Utensils": Utensils,
    "TrainFront": TrainFront,
    "Folder": Folder,
    "Gamepad": Gamepad,
    "CookingPot": CookingPot,
    "Speech": Speech,
    "Plane": Plane,
    "Armchair": Armchair,
    "Book": Book,
    "BriefcaseBusiness": BriefcaseBusiness,
    "Hospital": Hospital,
    "Lightbulb": Lightbulb,
    "Shirt": Shirt,
    "ShoppingCart": ShoppingCart,
    "Tags": Tags,
    "TramFront": TramFront,
    "Smartphone": Smartphone,
    "Wifi": Wifi,
    "Star": Star,
    "Vault": Vault,
    "Ghost": Ghost,
    "Monitor": Monitor,
    "BookImage": BookImage,
    "SquareTerminal": SquareTerminal,
    "Package": Package,
    "Music4": Music4,
    "FlameKindling": FlameKindling,
    "GlassWater": GlassWater,
    "Bot": Bot,
    "Coffee": Coffee,
    "AlarmClock": AlarmClock,
    "Plug": Plug,
    "PiggyBank": PiggyBank,
    "Gem": Gem,
    "WashingMachine": WashingMachine,
    "BedSingle": BedSingle,
    "Refrigerator": Refrigerator,
    "Rose": Rose,
    "Router": Router,
    "ToolCase": ToolCase,
    "Glasses": Glasses,
    "Cake": Cake,
    "Gift": Gift,
    "NotebookTabs": NotebookTabs,
    "Tickets": Tickets,
    "Wallet": Wallet,
    "Landmark": Landmark,
    "Projector": Projector,
    "Keyboard": Keyboard,
    "Headphones": Headphones,
    "Truck": Truck
};

export const AVAILABLE_ICONS = Object.keys(ICON_MAP);