import {
    Utensils,
    TrainFront,
    Folder,
    Gamepad,
    CookingPot,
    Speech,
    Plane,
    Armchair,
    Book,
    BriefcaseBusiness,
    Hospital,
    Lightbulb,
    Shirt,
    ShoppingCart,
    Tags,
    TramFront,
    Smartphone,
    Wifi,
    Star,
    Vault,
    Ghost,
    Monitor,
    BookImage,
    SquareTerminal,
    Package,
    Music4,
    FlameKindling,
    GlassWater,
    Bot,
    Coffee,
    AlarmClock,
    Plug,
    PiggyBank,
    Gem,
    WashingMachine,
    BedSingle,
    Refrigerator,
    Rose,
    Router,
    ToolCase,
    Glasses,
    Cake,
    Gift,
    NotebookTabs,
    Tickets,
    Wallet,
    Landmark,
    Projector,
    Keyboard,
    Headphones,
    Truck,
    Car,
    ShoppingBag,
    Heart,
    Dumbbell,
    Scissors,
    Tv,
    Laptop,
    GraduationCap,
    Camera,
    Sun,
    Bike,
    Dog,
    Cat,
    Baby,
    Home,
    MapPin,
    Smile,
    // 食べ物・飲み物
    Beer,
    Wine,
    Pizza,
    Sandwich,
    Apple,
    Cherry,
    Fish,
    IceCreamCone,
    Salad,
    Banana,
    Grape,
    Citrus,
    Egg,
    Beef,
    Milk,
    Wheat,
    CupSoda,
    Lollipop,
    // 天気・自然
    Snowflake,
    Cloud,
    Wind,
    Umbrella,
    Moon,
    Zap,
    Droplets,
    Flower,
    Flower2,
    Leaf,
    Mountain,
    Trees,
    TreePine,
    Sprout,
    Tent,
    Flame,
    // 動物・いきもの
    Bird,
    Rabbit,
    Bug,
    Turtle,
    Snail,
    Squirrel,
    PawPrint,
    // ツール・雑貨
    Wrench,
    Hammer,
    Axe,
    Anchor,
    Compass,
    Fuel,
    // スポーツ・ゲーム
    Trophy,
    Medal,
    Target,
    Swords,
    Crown,
    Wand2,
    Joystick,
    PartyPopper,
    Dice5,
    Clover,
    // 乗り物追加
    Bus,
    Ship,
    Rocket,
    // コミュニケーション
    Users,
    Bell,
    Flag,
    Megaphone,
    Film,
    // 医療・科学
    Stethoscope,
    Microscope,
    Thermometer,
    Pill,
    Barcode,
    // 追加50
    Ambulance,
    Anvil,
    Atom,
    Award,
    Backpack,
    Balloon,
    Bandage,
    Banknote,
    Bath,
    Bean,
    BedDouble,
    Binoculars,
    Brain,
    Brush,
    Building2,
    Candy,
    CandyCane,
    ChefHat,
    Clapperboard,
    CloudLightning,
    Coins,
    Construction,
    Cookie,
    Drum,
    EggFried,
    Fan,
    FireExtinguisher,
    FishingHook,
    Flashlight,
    Gamepad2,
    Guitar,
    Hourglass,
    Key,
    Laugh,
    Lock,
    Luggage,
    Magnet,
    Map,
    Martini,
    Pickaxe,
    Popcorn,
    Shield,

    Sparkles,
    TrafficCone,
    Waves,
    WandSparkles,
    Weight,
    Shrimp,
} from "lucide-react";

export const ICON_MAP = {
    "Utensils": Utensils,
    "TrainFront": TrainFront,
    "Folder": Folder,
    "Gamepad": Gamepad,
    "CookingPot": CookingPot,
    "Speech": Speech,
    "Plane": Plane,
    "Armchair": Armchair,
    "Book": Book,
    "BriefcaseBusiness": BriefcaseBusiness,
    "Hospital": Hospital,
    "Lightbulb": Lightbulb,
    "Shirt": Shirt,
    "ShoppingCart": ShoppingCart,
    "Tags": Tags,
    "TramFront": TramFront,
    "Smartphone": Smartphone,
    "Wifi": Wifi,
    "Star": Star,
    "Vault": Vault,
    "Ghost": Ghost,
    "Monitor": Monitor,
    "BookImage": BookImage,
    "SquareTerminal": SquareTerminal,
    "Package": Package,
    "Music4": Music4,
    "FlameKindling": FlameKindling,
    "GlassWater": GlassWater,
    "Bot": Bot,
    "Coffee": Coffee,
    "AlarmClock": AlarmClock,
    "Plug": Plug,
    "PiggyBank": PiggyBank,
    "Gem": Gem,
    "WashingMachine": WashingMachine,
    "BedSingle": BedSingle,
    "Refrigerator": Refrigerator,
    "Rose": Rose,
    "Router": Router,
    "ToolCase": ToolCase,
    "Glasses": Glasses,
    "Cake": Cake,
    "Gift": Gift,
    "NotebookTabs": NotebookTabs,
    "Tickets": Tickets,
    "Wallet": Wallet,
    "Landmark": Landmark,
    "Projector": Projector,
    "Keyboard": Keyboard,
    "Headphones": Headphones,
    "Truck": Truck,
    "Car": Car,
    "ShoppingBag": ShoppingBag,
    "Heart": Heart,
    "Dumbbell": Dumbbell,
    "Scissors": Scissors,
    "Tv": Tv,
    "Laptop": Laptop,
    "GraduationCap": GraduationCap,
    "Camera": Camera,
    "Sun": Sun,
    "Bike": Bike,
    "Dog": Dog,
    "Cat": Cat,
    "Baby": Baby,
    "Home": Home,
    "MapPin": MapPin,
    "Smile": Smile,
    // 食べ物・飲み物
    "Beer": Beer,
    "Wine": Wine,
    "Pizza": Pizza,
    "Sandwich": Sandwich,
    "Apple": Apple,
    "Cherry": Cherry,
    "Fish": Fish,
    "IceCreamCone": IceCreamCone,
    "Salad": Salad,
    "Banana": Banana,
    "Grape": Grape,
    "Citrus": Citrus,
    "Egg": Egg,
    "Beef": Beef,
    "Milk": Milk,
    "Wheat": Wheat,
    "CupSoda": CupSoda,
    "Lollipop": Lollipop,
    // 天気・自然
    "Snowflake": Snowflake,
    "Cloud": Cloud,
    "Wind": Wind,
    "Umbrella": Umbrella,
    "Moon": Moon,
    "Zap": Zap,
    "Droplets": Droplets,
    "Flower": Flower,
    "Flower2": Flower2,
    "Leaf": Leaf,
    "Mountain": Mountain,
    "Trees": Trees,
    "TreePine": TreePine,
    "Sprout": Sprout,
    "Tent": Tent,
    "Flame": Flame,
    // 動物・いきもの
    "Bird": Bird,
    "Rabbit": Rabbit,
    "Bug": Bug,
    "Turtle": Turtle,
    "Snail": Snail,
    "Squirrel": Squirrel,
    "PawPrint": PawPrint,
    // ツール
    "Wrench": Wrench,
    "Hammer": Hammer,
    "Axe": Axe,
    "Anchor": Anchor,
    "Compass": Compass,
    "Fuel": Fuel,
    // スポーツ・ゲーム
    "Trophy": Trophy,
    "Medal": Medal,
    "Target": Target,
    "Swords": Swords,
    "Crown": Crown,
    "Wand2": Wand2,
    "Joystick": Joystick,
    "PartyPopper": PartyPopper,
    "Dice5": Dice5,
    "Clover": Clover,
    // 乗り物追加
    "Bus": Bus,
    "Ship": Ship,
    "Rocket": Rocket,
    // コミュニケーション
    "Users": Users,
    "Bell": Bell,
    "Flag": Flag,
    "Megaphone": Megaphone,
    "Film": Film,
    // 医療・科学
    "Stethoscope": Stethoscope,
    "Microscope": Microscope,
    "Thermometer": Thermometer,
    "Pill": Pill,
    "Ambulance": Ambulance,
    "Bandage": Bandage,
    "Brain": Brain,
    "Weight": Weight,
    // 食べ物追加
    "ChefHat": ChefHat,
    "Bean": Bean,
    "EggFried": EggFried,
    "Cookie": Cookie,
    "Candy": Candy,
    "CandyCane": CandyCane,
    "Shrimp": Shrimp,
    "Martini": Martini,
    "Popcorn": Popcorn,
    // 住まい追加
    "Bath": Bath,
    "BedDouble": BedDouble,
    "Fan": Fan,
    "Key": Key,
    "Lock": Lock,
    "FireExtinguisher": FireExtinguisher,
    // お金・仕事追加
    "Banknote": Banknote,
    "Coins": Coins,
    "Building2": Building2,
    "Award": Award,
    "Construction": Construction,
    "Anvil": Anvil,
    "Pickaxe": Pickaxe,
    "Shield": Shield,
    // エンタメ追加
    "Clapperboard": Clapperboard,
    "Guitar": Guitar,
    "Drum": Drum,
    "Gamepad2": Gamepad2,
    "Balloon": Balloon,

    "Sparkles": Sparkles,
    "WandSparkles": WandSparkles,
    // アウトドア追加
    "Backpack": Backpack,
    "Binoculars": Binoculars,
    "FishingHook": FishingHook,
    "Flashlight": Flashlight,
    "Map": Map,
    "Luggage": Luggage,
    "TrafficCone": TrafficCone,
    // 自然追加
    "CloudLightning": CloudLightning,
    "Waves": Waves,
    // 科学
    "Atom": Atom,
    "Magnet": Magnet,
    "Brush": Brush,
    // その他
    "Hourglass": Hourglass,
    "Laugh": Laugh,
    "Barcode": Barcode,
};

export const AVAILABLE_ICONS = Object.keys(ICON_MAP);

export const ICON_GROUPS: { label: string; icons: string[] }[] = [
    {
        label: "食・飲み物",
        icons: ["Utensils", "CookingPot", "ChefHat", "Coffee", "GlassWater", "Cake", "Pizza", "Sandwich", "Salad", "Fish", "Beef", "Egg", "EggFried", "Bean", "Wheat", "Milk", "CupSoda", "Beer", "Wine", "Martini"],
    },
    {
        label: "フルーツ・スイーツ",
        icons: ["Apple", "Cherry", "Banana", "Grape", "Citrus", "IceCreamCone", "Lollipop", "Candy", "CandyCane", "Cookie", "Popcorn", "Shrimp"],
    },
    {
        label: "交通・移動",
        icons: ["TrainFront", "TramFront", "Plane", "Car", "Truck", "Bike", "Bus", "Ship", "Rocket", "Fuel", "MapPin", "Anchor", "TrafficCone"],
    },
    {
        label: "買い物",
        icons: ["ShoppingCart", "ShoppingBag", "Tags", "Package", "Shirt", "Gift", "Barcode"],
    },
    {
        label: "エンタメ・趣味",
        icons: ["Gamepad", "Gamepad2", "Joystick", "Music4", "Guitar", "Drum", "Tickets", "BookImage", "Projector", "Headphones", "Camera", "Tv", "Film", "Clapperboard", "Ghost", "Dice5", "PartyPopper", "Balloon", "Crown", "Wand2", "WandSparkles", "Swords", "Sparkles"],
    },
    {
        label: "住まい",
        icons: ["Home", "Armchair", "WashingMachine", "BedSingle", "BedDouble", "Refrigerator", "Bath", "Fan", "Plug", "FlameKindling", "Flame", "Router", "Wrench", "Hammer", "Key", "Lock", "Bell", "FireExtinguisher"],
    },
    {
        label: "テクノロジー",
        icons: ["Smartphone", "Wifi", "Monitor", "Laptop", "SquareTerminal", "Keyboard", "Bot"],
    },
    {
        label: "お金・仕事",
        icons: ["Wallet", "Vault", "PiggyBank", "Gem", "Landmark", "Banknote", "Coins", "BriefcaseBusiness", "Building2", "ToolCase", "Construction", "Anvil", "Pickaxe", "Speech", "Trophy", "Award", "Medal", "Shield", "Flag", "Megaphone"],
    },
    {
        label: "健康・美容",
        icons: ["Hospital", "Ambulance", "Heart", "Dumbbell", "Weight", "Rose", "Glasses", "Scissors", "Stethoscope", "Thermometer", "Pill", "Bandage", "Microscope", "Brain"],
    },
    {
        label: "学習・アート",
        icons: ["Book", "NotebookTabs", "Lightbulb", "GraduationCap", "Compass", "Target", "Atom", "Magnet", "Brush", "Backpack"],
    },
    {
        label: "自然・天気",
        icons: ["Sun", "Moon", "Snowflake", "Cloud", "CloudLightning", "Wind", "Umbrella", "Zap", "Droplets", "Waves", "Flower", "Flower2", "Leaf", "Mountain", "Trees", "TreePine", "Sprout", "Clover"],
    },
    {
        label: "アウトドア",
        icons: ["Tent", "Binoculars", "FishingHook", "Flashlight", "Map", "Luggage", "Axe"],
    },
    {
        label: "動物・いきもの",
        icons: ["Dog", "Cat", "Bird", "Rabbit", "Bug", "Turtle", "Snail", "Squirrel", "PawPrint"],
    },
    {
        label: "ペット・家族",
        icons: ["Baby", "Users", "Smile", "Laugh"],
    },
    {
        label: "その他",
        icons: ["Folder", "Star", "AlarmClock", "Hourglass"],
    },
];
