version: "3.8"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_db
    restart: always

  backend:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    environment:
      WATCHFILES_FORCE_POLLING: true
      DATABASE_URL: postgresql://user:password@db:5432/budget_db
  
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000 
      WATCHPACK_POLLING: "true"

volumes:
  postgres_data: