"""remove_account_type

Revision ID: 21cf46c7b4d5
Revises: 3f4679ffdbbc
Create Date: 2026-02-18 10:05:58.005855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cf46c7b4d5'
down_revision: Union[str, Sequence[str], None] = '3f4679ffdbbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('accounts', 'type')
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categories', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('goals', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sub_categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'sub_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'sub_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('sub_categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('goals', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('accounts', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('accounts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
