"""add icon_name

Revision ID: c594cc63297c
Revises: 5f200321fcb4
Create Date: 2026-03-19 08:01:43.497726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c594cc63297c'
down_revision: Union[str, Sequence[str], None] = '5f200321fcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon_name', sa.String(length=255), nullable=True))
    op.add_column('goals', sa.Column('icon_name', sa.String(length=255), nullable=True))
    op.add_column('sub_categories', sa.Column('icon_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_categories', 'icon_name')
    op.drop_column('goals', 'icon_name')
    op.drop_column('categories', 'icon_name')
    # ### end Alembic commands ###
